### ISSUE TITLE
Does not work on a Ryzen 2400G

### ISSUE THREAD

**Issue by txtsd** [BoukeHaarsma23/WattmanGTK#15] opened 2018-11-05 03:38 UTC
```
└─▶ ./wattman.py                                                                                   
Error during reading current states, WattmanGTK will not be able to continue :(
Please check if "cat /sys/class/drm/card0/device/pp_od_clk_voltage" returns something useful
```
The file exists, but it's empty. I don't have a dGPU. I've applied `amdgpu.featuremask=0xffffffff`.

What other info do you need to debug this?

EDIT:
```
└─▶ inxi -F                                                                                                                                                                                   
System:    Host: dungeon-of-data Kernel: 4.19.0-rc6-f97e5d0263ff x86_64 bits: 64 Desktop: Gnome 
           Distro: Arch Linux 
Machine:   Type: Desktop Mobo: Micro-Star model: B350 TOMAHAWK (MS-7A34) v: 1.0 serial: <root required> 
           UEFI: American Megatrends v: 1.H0 date: 05/02/2018 
CPU:       Topology: Quad Core model: AMD Ryzen 5 2400G with Radeon Vega Graphics bits: 64 type: MT MCP 
           L2 cache: 2048 KiB 
           Speed: 1720 MHz min/max: 1600/3600 MHz Core speeds (MHz): 1: 1407 2: 1404 3: 1410 4: 1413 5: 2300 
           6: 1969 7: 1670 8: 1459 
Graphics:  Device-1: AMD Raven Ridge [Radeon Vega Series / Radeon Vega Mobile Series] driver: amdgpu v: kernel 
           Display: server: X.Org 1.20.3 driver: none resolution: 1920x1080~60Hz 
           OpenGL: renderer: AMD RAVEN (DRM 3.27.0 4.19.0-rc6-f97e5d0263ff LLVM 8.0.0) 
           v: 4.5 Mesa 18.3.0-devel (git-9007c0ed26) 
Sensors:   System Temperatures: cpu: 43.1 C mobo: 39.0 C gpu: amdgpu temp: 43 C 
           Fan Speeds (RPM): fan-1: 0 fan-2: 1877 fan-3: 889 fan-4: 0 fan-5: 0 fan-6: 0 
Info:      Processes: 287 Uptime: 11h 28m Memory: 14.63 GiB used: 6.00 GiB (41.0%) Shell: zsh inxi: 3.0.26 

```

**Comment by clemej** [comment] 2018-11-05 03:55
Same here on Ryzen 5 PRO 2500U, which isn't surprising. 4.19 kernel.

**Comment by clemej** [comment] 2018-11-05 04:08
Oh, this is a dupe of Issue #9

**Comment by BoukeHaarsma23** [comment] 2018-11-05 07:21
Closing duplicate

**Closed by BoukeHaarsma23** 2018-11-05 07:21 UTC
